<footer>

<p>SOE Company</p>

<!-- Define the footer's navigation -->

<p id="footernavigation">
  <a href="index.php">Home</a>
  <a href="apply.php">Apply</a>
  <a href="jobs.php">Jobs</a>
  <a href="about.php">About</a>
  <a href="about.php#cardgrid01">Enhancements</a>
  <a href="about.php#MeetOurTeam">Profiles</a>
  <a href="phpenhancements.php">Manager Login</a>
</p>
<hr>
<p id = "footerlinks">
  <br>
  <a href="mailto:Contactus@SOECompany.com">Contact us</a>
  <br>
  <a href="termsandconditions.php">Terms and Conditions</a>
  <br>
  <a href="about.php#MeetOurTeam">Contributors</a>
</p>


<!-- Define the footer's follow us links -->

<div>
<p class="follow">
  Follow us
  <a href="https://www.facebook.com/" target="_blank">
    <img src="images/fb.png" alt="fb">
  </a>
  <a href="https://www.instagram.com/" target="_blank">
    <img src="images/ig.png" alt="ig">
  </a>
  <a href="https://www.linkedin.com/" target="_blank">
    <img src="images/in.png" alt="in">
  </a>
</p>

</div>
</footer>
