<div class="NavgationBar">
    <ul>
      <!-- Define the logo and navigation links -->
      <li><img src="images/SOE_logo_transparent_Small.png" alt="Logo"></li>
      <li><a href="index.php">Home</a></li>
      <li><a href="apply.php">Apply</a></li>
      <li><a href="jobs.php">Jobs</a></li>
      <li><a href="about.php">About</a></li>
      <li><a href="about.php#cardgrid01">Enhancements</a></li>
      <li><a href="about.php#MeetOurTeam">Profiles</a></li>
      <li><a href="mailto:104586973@student.swin.edu.au">Contact us</a></li>
    </ul>
  </div>